### ISSUE TITLE
Installation with Silex 2?

### ISSUE THREAD

**Issue by geoff-ellison** [Basster/silex-simple-swagger-provider#3]
Hi, and thanks for this great project. I have a question about installation:
The installation instructions are identical for both master branch and silex-2 branch. If I follow those, it will install the master branch. How to get composer to install the silex-2 branch?

Thanks

Geoff.

**Comment by Basster** [comment]
Thank you for the hint. I've updated the README.md of both, master and silex-2 branch, and also made the silex-2 branch default.

@geoff-ellison, are you able to install it now?

**Comment by geoff-ellison** [comment]
Yes, all good!
Thank you very much, closing this issue.

Cheers

Geoff.
